version: '2'

volumes:
  mongo_db:

services:
  web:
    build:
      context: .
    image: egorappweb
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    depends_on:
      - mongo
    env_file:
     - ./.env
    environment:
      DB_HOST: mongo
      PORT: 5000
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - mongo_db:/data/db
    restart: unless-stopped
