version: '2'

services:
  web:
    build:
      context: .
    image: egorappweb
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    depends_on:
      - mongo
    env_file:
     - ./.env
  mongo:
    image: mongo
